/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_lindenb_jbwa_jni_Example */

#ifndef _Included_com_github_lindenb_jbwa_jni_Example
#define _Included_com_github_lindenb_jbwa_jni_Example
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_github_lindenb_jbwa_jni_Example2 */

#ifndef _Included_com_github_lindenb_jbwa_jni_Example2
#define _Included_com_github_lindenb_jbwa_jni_Example2
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_github_lindenb_jbwa_jni_ExampleSEChangeMemOpt */

#ifndef _Included_com_github_lindenb_jbwa_jni_ExampleSEChangeMemOpt
#define _Included_com_github_lindenb_jbwa_jni_ExampleSEChangeMemOpt
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_github_lindenb_jbwa_jni_BwaIndex */

#ifndef _Included_com_github_lindenb_jbwa_jni_BwaIndex
#define _Included_com_github_lindenb_jbwa_jni_BwaIndex
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_github_lindenb_jbwa_jni_BwaIndex
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_github_lindenb_jbwa_jni_BwaIndex_close
  (JNIEnv *, jobject);

/*
 * Class:     com_github_lindenb_jbwa_jni_BwaIndex
 * Method:    _open
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_github_lindenb_jbwa_jni_BwaIndex__1open
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_github_lindenb_jbwa_jni_BwaMem */

#ifndef _Included_com_github_lindenb_jbwa_jni_BwaMem
#define _Included_com_github_lindenb_jbwa_jni_BwaMem
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_github_lindenb_jbwa_jni_BwaMem
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_github_lindenb_jbwa_jni_BwaMem_dispose
  (JNIEnv *, jobject);

/*
 * Class:     com_github_lindenb_jbwa_jni_BwaMem
 * Method:    mem_opt_init
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_github_lindenb_jbwa_jni_BwaMem_mem_1opt_1init
  (JNIEnv *, jclass);

/*
 * Class:     com_github_lindenb_jbwa_jni_BwaMem
 * Method:    update_score_parameters
 * Signature: (IIIIIII)V
 */
JNIEXPORT void JNICALL Java_com_github_lindenb_jbwa_jni_BwaMem_update_1score_1parameters
  (JNIEnv *, jobject, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     com_github_lindenb_jbwa_jni_BwaMem
 * Method:    update_more_parameters
 * Signature: (IIIII)V
 */
JNIEXPORT void JNICALL Java_com_github_lindenb_jbwa_jni_BwaMem_update_1more_1parameters
  (JNIEnv *, jobject, jint, jint, jint, jint, jint);

/*
 * Class:     com_github_lindenb_jbwa_jni_BwaMem
 * Method:    align
 * Signature: (Lcom/github/lindenb/jbwa/jni/BwaIndex;[B)[Lcom/github/lindenb/jbwa/jni/AlnRgn;
 */
JNIEXPORT jobjectArray JNICALL Java_com_github_lindenb_jbwa_jni_BwaMem_align
  (JNIEnv *, jobject, jobject, jbyteArray);

/*
 * Class:     com_github_lindenb_jbwa_jni_BwaMem
 * Method:    align2
 * Signature: (Lcom/github/lindenb/jbwa/jni/BwaIndex;[Lcom/github/lindenb/jbwa/jni/ShortRead;[Lcom/github/lindenb/jbwa/jni/ShortRead;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_github_lindenb_jbwa_jni_BwaMem_align2
  (JNIEnv *, jobject, jobject, jobjectArray, jobjectArray);

/*
 * Class:     com_github_lindenb_jbwa_jni_BwaMem
 * Method:    alignR
 * Signature: (Lcom/github/lindenb/jbwa/jni/BwaIndex;[Lcom/github/lindenb/jbwa/jni/ShortRead;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_github_lindenb_jbwa_jni_BwaMem_alignR
  (JNIEnv *, jobject, jobject, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_github_lindenb_jbwa_jni_KSeq */

#ifndef _Included_com_github_lindenb_jbwa_jni_KSeq
#define _Included_com_github_lindenb_jbwa_jni_KSeq
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_github_lindenb_jbwa_jni_KSeq
 * Method:    next
 * Signature: ()Lcom/github/lindenb/jbwa/jni/ShortRead;
 */
JNIEXPORT jobject JNICALL Java_com_github_lindenb_jbwa_jni_KSeq_next
  (JNIEnv *, jobject);

/*
 * Class:     com_github_lindenb_jbwa_jni_KSeq
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_github_lindenb_jbwa_jni_KSeq_dispose
  (JNIEnv *, jobject);

/*
 * Class:     com_github_lindenb_jbwa_jni_KSeq
 * Method:    init
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_github_lindenb_jbwa_jni_KSeq_init
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_github_lindenb_jbwa_jni_ShortRead */

#ifndef _Included_com_github_lindenb_jbwa_jni_ShortRead
#define _Included_com_github_lindenb_jbwa_jni_ShortRead
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_github_lindenb_jbwa_jni_AlnRgn */

#ifndef _Included_com_github_lindenb_jbwa_jni_AlnRgn
#define _Included_com_github_lindenb_jbwa_jni_AlnRgn
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_github_lindenb_jbwa_jni_BwaFrame */

#ifndef _Included_com_github_lindenb_jbwa_jni_BwaFrame
#define _Included_com_github_lindenb_jbwa_jni_BwaFrame
#ifdef __cplusplus
extern "C" {
#endif
#undef com_github_lindenb_jbwa_jni_BwaFrame_FOCUS_TRAVERSABLE_UNKNOWN
#define com_github_lindenb_jbwa_jni_BwaFrame_FOCUS_TRAVERSABLE_UNKNOWN 0L
#undef com_github_lindenb_jbwa_jni_BwaFrame_FOCUS_TRAVERSABLE_DEFAULT
#define com_github_lindenb_jbwa_jni_BwaFrame_FOCUS_TRAVERSABLE_DEFAULT 1L
#undef com_github_lindenb_jbwa_jni_BwaFrame_FOCUS_TRAVERSABLE_SET
#define com_github_lindenb_jbwa_jni_BwaFrame_FOCUS_TRAVERSABLE_SET 2L
#undef com_github_lindenb_jbwa_jni_BwaFrame_TOP_ALIGNMENT
#define com_github_lindenb_jbwa_jni_BwaFrame_TOP_ALIGNMENT 0.0f
#undef com_github_lindenb_jbwa_jni_BwaFrame_CENTER_ALIGNMENT
#define com_github_lindenb_jbwa_jni_BwaFrame_CENTER_ALIGNMENT 0.5f
#undef com_github_lindenb_jbwa_jni_BwaFrame_BOTTOM_ALIGNMENT
#define com_github_lindenb_jbwa_jni_BwaFrame_BOTTOM_ALIGNMENT 1.0f
#undef com_github_lindenb_jbwa_jni_BwaFrame_LEFT_ALIGNMENT
#define com_github_lindenb_jbwa_jni_BwaFrame_LEFT_ALIGNMENT 0.0f
#undef com_github_lindenb_jbwa_jni_BwaFrame_RIGHT_ALIGNMENT
#define com_github_lindenb_jbwa_jni_BwaFrame_RIGHT_ALIGNMENT 1.0f
#undef com_github_lindenb_jbwa_jni_BwaFrame_serialVersionUID
#define com_github_lindenb_jbwa_jni_BwaFrame_serialVersionUID -7644114512714619750LL
#undef com_github_lindenb_jbwa_jni_BwaFrame_serialVersionUID
#define com_github_lindenb_jbwa_jni_BwaFrame_serialVersionUID 4613797578919906343LL
#undef com_github_lindenb_jbwa_jni_BwaFrame_INCLUDE_SELF
#define com_github_lindenb_jbwa_jni_BwaFrame_INCLUDE_SELF 1L
#undef com_github_lindenb_jbwa_jni_BwaFrame_SEARCH_HEAVYWEIGHTS
#define com_github_lindenb_jbwa_jni_BwaFrame_SEARCH_HEAVYWEIGHTS 1L
#undef com_github_lindenb_jbwa_jni_BwaFrame_OPENED
#define com_github_lindenb_jbwa_jni_BwaFrame_OPENED 1L
#undef com_github_lindenb_jbwa_jni_BwaFrame_serialVersionUID
#define com_github_lindenb_jbwa_jni_BwaFrame_serialVersionUID 4497834738069338734LL
#undef com_github_lindenb_jbwa_jni_BwaFrame_DEFAULT_CURSOR
#define com_github_lindenb_jbwa_jni_BwaFrame_DEFAULT_CURSOR 0L
#undef com_github_lindenb_jbwa_jni_BwaFrame_CROSSHAIR_CURSOR
#define com_github_lindenb_jbwa_jni_BwaFrame_CROSSHAIR_CURSOR 1L
#undef com_github_lindenb_jbwa_jni_BwaFrame_TEXT_CURSOR
#define com_github_lindenb_jbwa_jni_BwaFrame_TEXT_CURSOR 2L
#undef com_github_lindenb_jbwa_jni_BwaFrame_WAIT_CURSOR
#define com_github_lindenb_jbwa_jni_BwaFrame_WAIT_CURSOR 3L
#undef com_github_lindenb_jbwa_jni_BwaFrame_SW_RESIZE_CURSOR
#define com_github_lindenb_jbwa_jni_BwaFrame_SW_RESIZE_CURSOR 4L
#undef com_github_lindenb_jbwa_jni_BwaFrame_SE_RESIZE_CURSOR
#define com_github_lindenb_jbwa_jni_BwaFrame_SE_RESIZE_CURSOR 5L
#undef com_github_lindenb_jbwa_jni_BwaFrame_NW_RESIZE_CURSOR
#define com_github_lindenb_jbwa_jni_BwaFrame_NW_RESIZE_CURSOR 6L
#undef com_github_lindenb_jbwa_jni_BwaFrame_NE_RESIZE_CURSOR
#define com_github_lindenb_jbwa_jni_BwaFrame_NE_RESIZE_CURSOR 7L
#undef com_github_lindenb_jbwa_jni_BwaFrame_N_RESIZE_CURSOR
#define com_github_lindenb_jbwa_jni_BwaFrame_N_RESIZE_CURSOR 8L
#undef com_github_lindenb_jbwa_jni_BwaFrame_S_RESIZE_CURSOR
#define com_github_lindenb_jbwa_jni_BwaFrame_S_RESIZE_CURSOR 9L
#undef com_github_lindenb_jbwa_jni_BwaFrame_W_RESIZE_CURSOR
#define com_github_lindenb_jbwa_jni_BwaFrame_W_RESIZE_CURSOR 10L
#undef com_github_lindenb_jbwa_jni_BwaFrame_E_RESIZE_CURSOR
#define com_github_lindenb_jbwa_jni_BwaFrame_E_RESIZE_CURSOR 11L
#undef com_github_lindenb_jbwa_jni_BwaFrame_HAND_CURSOR
#define com_github_lindenb_jbwa_jni_BwaFrame_HAND_CURSOR 12L
#undef com_github_lindenb_jbwa_jni_BwaFrame_MOVE_CURSOR
#define com_github_lindenb_jbwa_jni_BwaFrame_MOVE_CURSOR 13L
#undef com_github_lindenb_jbwa_jni_BwaFrame_NORMAL
#define com_github_lindenb_jbwa_jni_BwaFrame_NORMAL 0L
#undef com_github_lindenb_jbwa_jni_BwaFrame_ICONIFIED
#define com_github_lindenb_jbwa_jni_BwaFrame_ICONIFIED 1L
#undef com_github_lindenb_jbwa_jni_BwaFrame_MAXIMIZED_HORIZ
#define com_github_lindenb_jbwa_jni_BwaFrame_MAXIMIZED_HORIZ 2L
#undef com_github_lindenb_jbwa_jni_BwaFrame_MAXIMIZED_VERT
#define com_github_lindenb_jbwa_jni_BwaFrame_MAXIMIZED_VERT 4L
#undef com_github_lindenb_jbwa_jni_BwaFrame_MAXIMIZED_BOTH
#define com_github_lindenb_jbwa_jni_BwaFrame_MAXIMIZED_BOTH 6L
#undef com_github_lindenb_jbwa_jni_BwaFrame_serialVersionUID
#define com_github_lindenb_jbwa_jni_BwaFrame_serialVersionUID 2673458971256075116LL
#undef com_github_lindenb_jbwa_jni_BwaFrame_EXIT_ON_CLOSE
#define com_github_lindenb_jbwa_jni_BwaFrame_EXIT_ON_CLOSE 3L
#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_github_lindenb_jbwa_jni_BwaFrame_AlnTableModel */

#ifndef _Included_com_github_lindenb_jbwa_jni_BwaFrame_AlnTableModel
#define _Included_com_github_lindenb_jbwa_jni_BwaFrame_AlnTableModel
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
