#!/usr/bin/perl -w
## align BisulfiteHiC paired-end reads to genome. Genome needs to be indexed first
## author: Yaping Liu  lyping1986@gmail.com

use strict;
use Getopt::Long;
use File::Basename;

sub usage {

    print STDERR "\nUsage:\n";
    print STDERR "bisulfitehicMap [Options] genome.fa output.bam r1.fq[.gz] r2.fq[.gz]\n\n";

    print STDERR " Align BisulfiteHiC paired-end reads to genome. Genome needs to be indexed first\n";
   

	
	print STDERR "  [Options]:\n\n";
 	print STDERR " #####General option:\n\n";
 	print STDERR "  --cpu NUM: number of CPU to use.(Default: 1)\n\n";
 	print STDERR "  --mem NUM: number of Gigabytes to use.(Default: 10)\n\n";
 	print STDERR "  --buffer NUM: number of reads to buffer in memory.(Default: 100000)\n\n";
 	print STDERR "  --score NUM: minimum aligntment score to use. equal to -T in bwa mem.(Default: 0)\n\n";
 	print STDERR "  ---clip5 NUM: bp at 5' end to clip.(Default: 0)\n\n";
 	print STDERR "  ---clip3 NUM: bp at 5' end to clip.(Default: 0)\n\n";
 	print STDERR "  --rgId STR: readgroup ID to add.(Default: null)\n\n";
 	print STDERR "  --rgSm STR: readgroup SM to add.(Default: null)\n\n";
 	
 	 exit(1);
}

##default option setting
my $cpu=1;
my $mem=10;
my $buffer=100000;
my $score=0;
my $clip5=0;
my $clip3=0;
my $rgId="";
my $rgSm="";
my $bisulfitehic_path=`echo \$BISHIC`;
chomp($bisulfitehic_path);

print STDERR "bisulfitehicMap ";
my $cmd_root=join " ", @ARGV;
print STDERR "$cmd_root\n\n";

GetOptions( 
			"cpu=i" => \$cpu,
			"mem=i" => \$mem,
			"buffer=i" => \$buffer,
			"score=i" => \$score,
			"clip5=i" => \$clip5,
			"clip3=i" => \$clip3,
			"rgId=s" => \$rgId,
			"rgSm=s" => \$rgSm,
			
);

usage() if ( scalar(@ARGV) == 0 );

if ( scalar(@ARGV) < 4 ) {
    print STDERR "Wrong number of arguments\n";
    usage();
}
my $genome=$ARGV[0];
my $output=$ARGV[1];
my $r1=$ARGV[2];
my $r2=$ARGV[3];

my $cmd = "java -Xmx${mem}G -Djava.library.path=${bisulfitehic_path}/jbwa/jbwa-1.0.0/src/main/native/ -cp \"${bisulfitehic_path}/target/bisulfitehic-default.jar:${bisulfitehic_path}/jbwa/jbwa-1.0.0/jbwa.jar\" main.java.edu.mit.compbio.bisulfitehic.mapping.Bhmem ";
#my $cmd = "java -Xmx${mem}G -Djava.library.path=${bisulfitehic_path}/jbwa/src/main/native/ -cp \"${bisulfitehic_path}/target/bisulfitehic-0.02-jar-with-dependencies.jar:${bisulfitehic_path}/jbwa/jbwa-1.0.0/jbwa.jar\" main.java.edu.mit.compbio.bisulfitehic.mapping.Bhmem ";

$cmd.="$genome $output $r1 $r2 -t $cpu -score $score -buffer $buffer -clip5 $clip5 -clip3 $clip3 ";
if($rgId ne "" and $rgSm ne ""){
	$cmd.="-rgId $rgId -rgSm $rgSm ";
}
$cmd.="\n";

print STDERR "$cmd\n";
system($cmd)==0 || die "can't execute $cmd: $!\n";





